### ISSUE TITLE
Nice Theme!

### ISSUE THREAD

**Issue by LucidNyxx** [warrayquipsome/NOVATURIENT#1]
This is an eye-catching theme. It's so good and well put together. I just have two things to say real quick, haha. One, is there a way to remove the Horizontal server list, and two, to make the member list be out all the time instead of hovering over it?

Thanks!

**Comment by warrayquipsome** [comment]
ye i have just edited the theme you can delete @import url("https://warrayquipsome.github.io/NOVATURIENT/HorizontalServer.css"); for vertical server list and delete 
/*avatar only member list*/
.membersWrap-2h-GB4 {
  min-width: unset;
}
.membersWrap-2h-GB4 .members-1998pB {
  max-width: 65px;
  min-width: 65px;
  -webkit-transition: .3s ease;
  transition: .3s ease;
}
.membersWrap-2h-GB4 .members-1998pB:hover {
  max-width: 240px;
  min-width: 240px;
}
.membersWrap-2h-GB4 .members-1998pB .content-3YMskv:not(:hover) {
  padding-top: 10px;
}
.membersGroup-v9BXpm {
  transition: .3s ease;
}
.membersWrap-2h-GB4:not(:hover) .membersGroup-v9BXpm {
  height: 0px;
  opacity: 0;
  padding: 0%;
  transition: .3s ease;
}
for not having the hover to show members, thx for the support!
