### ISSUE TITLE
 Addon removal from website notice and reason.

### ISSUE THREAD

**Issue by itmesarah** [warrayquipsome/NOVATURIENT#6]
Your addon has been broken, outdated or otherwise unusable for an extended period of time where we feel it has had plenty of time and opportunity to be fixed, if you wish to have it back on the site, you'll need to fix and resubmit it once the issue has been fixed.

**Comment by warrayquipsome** [comment]
hi Sarah, i been really thinking a lot about this and i decided that its best not to continue this theme and im gonna set this repository to private forever. Sorry for the late reply as well
